### ISSUE TITLE
4 new firmware versions in Fritzbox 7490 image

### ISSUE THREAD

**Issue by hailfinger** [xdarklight/lantiq-xdsl-firmware-info#10]
URL: http://ftp.avm.de/fritz.box/fritzbox.7490/firmware/deutsch/FRITZ.Box_7490.113.06.90.image

Extraction:
7z e FRITZ.Box_7490.113.06.90.image -r filesystem.image
7z e filesystem.image filesystem_core.squashfs
unsquashfs4-avm-be filesystem_core.squashfs -e lib/modules/dsp_vr9/
cd lib/modules/dsp_vr9/
bspatch vr9-B-dsl.bin vr9-A-dsl.bin vr9-A-dsl.bin.bsdiff
bspatch vr9-B-dsl.bin release-vr9-B-dsl.bin release-vr9-B-dsl.bin.bsdiff 
bspatch vr9-A-dsl.bin release-vr9-A-dsl.bin release-vr9-A-dsl.bin.bsdiff 

Results:
(please note that although some version numbers are already known, the binaries are different)

filename: release-vr9-B-dsl.bin
version: 5.7.8.9.1.7-5.7.2.4.1.2
sha1sum: 539162673a99a05d8343da06bebe7e6c356f0a7d
filesize: 896592

filename: release-vr9-A-dsl.bin
version: 5.7.8.9.1.7-5.7.1.E.1.1
sha1sum: b4c811ce46f6606f93165d03cc125e8db1d88038
filesize: 913736

filename: vr9-A-dsl.bin
version: 5.9.0.C.1.7-5.9.0.A.0.1
sha1sum: d5744613981e3ff9cec19481eee3bb301670129b
filesize: 925492

filename: vr9-B-dsl.bin
version: 5.9.0.C.1.7-5.9.0.A.0.2
sha1sum: ef3237c2345487f69b02592a9373bdcbcd04547c
filesize: 907204

**Comment by bobbib** [comment]
404 Not Found.
Although `FRITZ.Box_7490.113.06.92.image` is there.

**Comment by hailfinger** [comment]
URL: http://download.avm.de/fritzbox/fritzbox-7490/deutschland/fritz.os/FRITZ.Box_7490.113.06.93.image

Extraction:
7z e FRITZ.Box_7490.113.06.93.image -r filesystem.image
7z e filesystem.image filesystem_core.squashfs
unsquashfs4-avm-be filesystem_core.squashfs -e lib/modules/dsp_vr9/
cd squashfs-root/lib/modules/dsp_vr9/
bspatch vr9-B-dsl.bin vr9-A-dsl.bin vr9-A-dsl.bin.bsdiff
bspatch vr9-B-dsl.bin release-vr9-B-dsl.bin release-vr9-B-dsl.bin.bsdiff
bspatch vr9-A-dsl.bin release-vr9-A-dsl.bin release-vr9-A-dsl.bin.bsdiff


filename: release-vr9-B-dsl.bin
version: 5.7.8.9.1.7-5.7.2.4.1.2
sha1sum: 539162673a99a05d8343da06bebe7e6c356f0a7d
filesize: 896592

filename: release-vr9-A-dsl.bin
version: 5.7.8.9.1.7-5.7.1.E.1.1
sha1sum: b4c811ce46f6606f93165d03cc125e8db1d88038
filesize: 913736

filename: vr9-A-dsl.bin
version: 5.9.0.C.1.7-5.9.0.A.0.1
sha1sum: 808f84be92e6d38994cc5d52f274c5e3a924e1e2
filesize: 925516

filename: vr9-B-dsl.bin
version: 5.9.0.C.1.7-5.9.0.A.0.2
sha1sum: b27fd50c83587aa5d80ee63f9d4ea4e8af30da00
filesize: 907232

**Comment by Finomosec** [comment]
Hi there! I'm having trouble extracting the latest version of this:
wget https://download.avm.de/fritzbox/fritzbox-7490/deutschland/fritz.os/FRITZ.Box_7490-07.60.image
7z e FRITZ.Box_7490-07.60.image -r filesystem.image # ok

7z e filesystem.image filesystem_core.squashfs
```
7-Zip 23.01 (x64) : Copyright (c) 1999-2023 Igor Pavlov : 2023-06-20
 64-bit locale=de_DE.UTF-8 Threads:32 OPEN_MAX:1024

Scanning the drive for archives:
1 file, 35008520 bytes (34 MiB)

Extracting archive: filesystem.image
         
ERRORS:
There are data after the end of archive

--
Path = filesystem.image
Type = xz
ERRORS:
There are data after the end of archive
Offset = 96
Physical Size = 278964
Tail Size = 34729460
Method = LZMA2:16
Streams = 10
Blocks = 10
Characteristics = BlockPackSize BlockUnpackSize

No files to process

Archives with Errors: 1

Open Errors: 1
```
```
file filesystem.image 
filesystem.image: Squashfs filesystem, big endian, version 4.0, xz compressed, 35007698 bytes, 105 inodes, blocksize: 65536 bytes, created: Wed Feb 10 04:21:38 1971
```

I believe it might be due to the BIG ENDIAN. But did this actually change over time? I mean the hardware cannot switch endians, can it? So it must have been the same endian all along.

I have spent over 4 hours to try and solve this already... any help would be appreciated. 


And next question: Where to get `unsquashfs4-avm-be`?

**Comment by bobbib** [comment]
It looks like a custom _squashfs_ version; try to unpack that `filesystem.image` with `unsquashfs4-avm-be` directly...

> And next question: Where to get `unsquashfs4-avm-be`?

https://github.com/xdarklight/lantiq-xdsl-firmware-info/issues/22
https://github.com/plougher/squashfs-tools/issues/263
