### ISSUE TITLE
new firmware VDSL over ISDN incl. vectoring support for VRX200, version: 6.8.6 | ADSL Annex B for VRX200, version: 6.7.A

### ISSUE THREAD

**Issue by dangowrt** [xdarklight/lantiq-xdsl-firmware-info#13]
found in https://www.telekom.de/hilfe/downloads/firmware-speedport-w921v-1.44.000.bin
using w921v_fw_cutter (had to rename the file, but it worked just as it did for 1.21.000)

**Comment by xdarklight** [comment]
that download link is not available anymore

**Comment by dangowrt** [comment]
updated link: https://www.telekom.de/hilfe/downloads/firmware-speedport-w921v-1.45.000.bin

**Comment by xdarklight** [comment]
thanks!
