### ISSUE TITLE
VDSL w/ vectoring 9.1.4, ADSL 9.0.D, annex A and B

### ISSUE THREAD

**Issue by hardfalcon** [xdarklight/lantiq-xdsl-firmware-info#14]
The latest "Labor" [firmware](https://ftp.avm.de/fritzbox/beta/netze/fritzbox-7490-beta-54213.zip) for the Fritzbox 7490 contains the following:

```
vr9-A-dsl.bin: VDSL over ISDN incl. vectoring support for VRX200, version: 9.1.4 | ADSL Annex A for VRX200, version: 9.0.D
vr9-B-dsl.bin: VDSL over ISDN incl. vectoring support for VRX200, version: 9.1.4 | ADSL Annex B for VRX200, version: 9.0.D
```

The annex A firmware is shipped as a bsdiff to the annex B firmware image.

I've tested the annex B firmware successfully on a TP-Link VR200v.

**Comment by just2mad** [comment]
Hi, I don't understand why the bspatched are needed.
Is this to be compatible with Annex A and Annex B in one file?
Or is this for performance? What exactly is the points of the patching?

Thanks!

**Comment by hardfalcon** [comment]
@just2mad: Think of bspatch as a "binary diff" between the annex A firmware blob an the annex B firmware blob for the DSL modem inside the router.
By using bspatch, only either the annex A or the annex B firmware blob needs to be included in full, and the "full" firmware blob for the other annex can simply be obtained at runtime/during boot by applying the bspatch to the "full" firmware blob for the "first" annex. It's just a simple and efficient way to save a lot of space in the router's firmware image whilst still allowing the device vendor to support both DSL annexes with one common firmware.

**Comment by Lankaster** [comment]
Annex B, vectoring work very well on BT Home Hub 5A (openwrt-trunk):
```
ATU-C Vendor ID:                          Broadcom 192.85
ATU-C System Vendor ID:                   Broadcom
Chipset:                                  Lantiq-VRX200
Firmware Version:                         5.9.1.4.0.7
API Version:                              4.17.18.6
XTSE Capabilities:                        0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x2
Annex:                                    B
Line Mode:                                G.993.5 (VDSL2 with down- and upstream vectoring)
Profile:                                  17a
Line State:                               UP [0x801: showtime_tc_sync]
Forward Error Correction Seconds (FECS):  Near: 0 / Far: 43
Errored seconds (ES):                     Near: 0 / Far: 3
Severely Errored Seconds (SES):           Near: 0 / Far: 0
Loss of Signal Seconds (LOSS):            Near: 0 / Far: 0
Unavailable Seconds (UAS):                Near: 100 / Far: 100
Header Error Code Errors (HEC):           Near: 0 / Far: 0
Non Pre-emtive CRC errors (CRC_P):        Near: 0 / Far: 0
Pre-emtive CRC errors (CRCP_P):           Near: 0 / Far: 0
Power Management Mode:                    L0 - Synchronized
Latency [Interleave Delay]:               0.14 ms [Fast]   0.0 ms [Fast]
Data Rate:                                Down: 90.760 Mb/s / Up: 33.706 Mb/s
Line Attenuation (LATN):                  Down: 12.6 dB / Up: 11.1 dB
Signal Attenuation (SATN):                Down: 12.6 dB / Up: 10.9 dB
Noise Margin (SNR):                       Down: 8.0 dB / Up: 10.6 dB
Aggregate Transmit Power (ACTATP):        Down: -1.0 dB / Up: 12.4 dB
Max. Attainable Data Rate (ATTNDR):       Down: 103.579 Mb/s / Up: 36.770 Mb/s
Line Uptime Seconds:                      280
Line Uptime:                              4m 40s
```

**Comment by just2mad** [comment]
So vectoring is included in openwrt now?
What are you data rates? Do you reach the 90 Mbit/s in download?

**Comment by Lankaster** [comment]
@just2mad no, this version isn't include into openwrt, but you can extract from labor firmware it self. 
Yes, i reach about 85Mbit. My DSL line is really bad and i should set the ds_snr_offset '20' for stable connection.  ( https://www.dslreports.com/speedtest/33585346 , https://openwrt.org/toh/bt/homehub_v5a?s[]=bt&s[]=hub&s[]=5#und1_germany_vdsl2_annex_b_example ) 
I think it's possible reach the 100 Mbit/s on good dsl line.

**Comment by just2mad** [comment]
@Lankaster as I read somewhere in lede forum, there are throughput problems with bandwidths above 50?Mbit/s in the lantiq chipset!

**Comment by Lankaster** [comment]
@just2mad at first BT5 haven't VMMC, second: BT5 have a SMP (dualcore) I think it's enough for 100Mbit/s WAN. With SQM shaping i have about 55-70 Mbit/s, but 100% CPU load. Because of CPU load i don't use a shaping. Via WiFi ( AC ) i reach about 20MB/s between my Tablet and NAS (160Mbit/sec). 
I am happy with my BT5    :--)

**Comment by Lankaster** [comment]
@xdarklight Can we add information about new DSL Firmware ?
```
bk@tt:~/Projects/lantiq-xdsl-firmware-info$ ./ltq-xdsl-fw-info.sh
ltq-xdsl-fw-info.sh: UNKNOWN application type () for UNKNOWN platform (), version: .. | UNKNOWN application type () for UNKNOWN platform (), version: ..
vr9-B-dsl.bin: VDSL over ISDN incl. vectoring support for VRX200, version: 9.1.4 | ADSL Annex B for VRX200, version: 9.0.D
release-vr9-A-dsl.bin: VDSL over ISDN incl. vectoring support for VRX200, version: 7.8.9 | ADSL Annex A for VRX200, version: 7.1.E
vr9-A-dsl.bin: VDSL over ISDN incl. vectoring support for VRX200, version: 9.1.4 | ADSL Annex A for VRX200, version: 9.0.D
release-vr9-B-dsl.bin: VDSL over ISDN incl. vectoring support for VRX200, version: 7.8.9 | ADSL Annex B for VRX200, version: 7.2.4

bk@tt:~/Projects/lantiq-xdsl-firmware-info$ sha1sum *bin
b4c811ce46f6606f93165d03cc125e8db1d88038  release-vr9-A-dsl.bin
539162673a99a05d8343da06bebe7e6c356f0a7d  release-vr9-B-dsl.bin
33bcae8d8b213f3e6213d4553c8e7330fc8512c9  vr9-A-dsl.bin
3c97762499817686c688b71724ab6a329daa81f8  vr9-B-dsl.bin

bk@tt:~/Projects/lantiq-xdsl-firmware-info$ ls -la | grep bin
-rw-r--r--  1 bk bk 913736 Aug 27 21:42 release-vr9-A-dsl.bin
-rw-r--r--  1 bk bk 896592 Aug 27 21:42 release-vr9-B-dsl.bin
-rw-r--r--  1 bk bk 926364 Aug 27 21:42 vr9-A-dsl.bin
-r-xr-xr-x  1 bk bk 908164 Aug 17 16:04 vr9-B-dsl.bin
```

**Comment by alanswanson** [comment]
Just to add this is working with ADSL annex A on a TP-Link 8970 in the UK (pending VDSL2 vectoring sometime in the future).

However compared to redistributable 8.0.B, the data rate is the same but the line and signal attenuation are wrong dropping from 26-27dB to 10-12dB for a 13Mb/s connection. Firmware API version remains the same so looks a firmware bug.

**Comment by BigNerd95** [comment]
What is the difference between Release and Pre-release?

**Comment by stonerl** [comment]
The firmware can also be found in [this stable release](https://download.avm.de/fritzbox/fritzbox-7490/deutschland/fritz.os/FRITZ.Box_7490.113.07.01.image) for the 7490.

`vr9-B-dsl.bin: VDSL over ISDN incl. vectoring support for VRX200, version: 9.1.4 | ADSL Annex B for VRX200, version: 9.0.D`

**Comment by Borromini** [comment]
Verbose script output:

```
filename: vr9-A-dsl.bin
version: 5.9.1.4.0.7-5.9.0.D.0.1
sha1sum: 33bcae8d8b213f3e6213d4553c8e7330fc8512c9
filesize: 926364
Firmware1:
	PLATFORM: 5
	PLATFORM_STR: VRX200
	APPLICATION_TYPE: 7
	APPLICATION_TYPE_STR: VDSL over ISDN incl. vectoring support
	VERSION_STR: 9.1.4
	RELEASE_STATUS: 0
	RELEASE_STATUS_STR: Release
Firmware2:
	PLATFORM: 5
	PLATFORM_STR: VRX200
	APPLICATION_TYPE: 1
	APPLICATION_TYPE_STR: ADSL Annex A
	VERSION_STR: 9.0.D
	RELEASE_STATUS: 0
	RELEASE_STATUS_STR: Release

filename: vr9-B-dsl.bin
version: 5.9.1.4.0.7-5.9.0.D.0.2
sha1sum: 3c97762499817686c688b71724ab6a329daa81f8
filesize: 908164
Firmware1:
	PLATFORM: 5
	PLATFORM_STR: VRX200
	APPLICATION_TYPE: 7
	APPLICATION_TYPE_STR: VDSL over ISDN incl. vectoring support
	VERSION_STR: 9.1.4
	RELEASE_STATUS: 0
	RELEASE_STATUS_STR: Release
Firmware2:
	PLATFORM: 5
	PLATFORM_STR: VRX200
	APPLICATION_TYPE: 2
	APPLICATION_TYPE_STR: ADSL Annex B
	VERSION_STR: 9.0.D
	RELEASE_STATUS: 0
	RELEASE_STATUS_STR: Release
```

**Comment by nouman8** [comment]
A new release is out http://download.avm.de/fritzbox/fritzbox-7490/deutschland/fritz.os/ 
can some check if there's any new version.

**Comment by pstlr78** [comment]
> 
> 
> A new release is out http://download.avm.de/fritzbox/fritzbox-7490/deutschland/fritz.os/
> can someone check if there's any new version.

I just checked image 07.11:

release-vr9-A-dsl.bin and release-vr9-B-dsl.bin are identical to the ones above. Even the checksum is the same.

vr9-A-dsl.bin and vr9-B-dsl.bin do have the same firmware version as above (5.**9.1.4**.0.7), but the checksum is not the same as before. I do not know how I could check the ADSL firmware version (the second part : i.e. 9.0.D) as I am running VDSL.

I assume that even if there is some difference this should be minor.

**Comment by nouman8** [comment]
Thanks for quick reply...can you plz do the same for the following firmware which also apparently is for vr9 chip.
http://download.avm.de/fritzbox/fritzbox-7362-sl/deutschland/fritz.os/

**Comment by Lankaster** [comment]
@nouman8 It's same version:
```
root@OpenWrt:~# sha256sum /lib/firmware/vr9-B-dsl.bin 
e408f82323fa60356d1c35df5b781f88d3fad830c7c6a55f798682e16316b939  /lib/firmware/vr9-B-dsl.bin
```
hier is DSL status
```
Chipset:                                  Lantiq-VRX200
Firmware Version:                         5.9.1.4.0.7
API Version:                              4.17.18.6
XTSE Capabilities:                        0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x2
Annex:                                    B
Line Mode:                                G.993.5 (VDSL2 with down- and upstream vectoring)
Profile:                                  17a
Line State:                               UP [0x801: showtime_tc_sync]
```

@pstlr78 I will check the ADSL version this week

**Comment by Janaue** [comment]
I have a homehub 5a with the chip xrx200. My internet connection use adsl annex A, but I am confused over the various versions here http://xdarklight.github.io/lantiq-xdsl-firmware-info/

which one is the latest ? is it 9.0.A ?

is there a version which copes well with a very bad ADSL connection (line length 3km and 55dB of attenuation?

**Comment by Lankaster** [comment]
ADSL:
```
Chipset:                                  Lantiq-VRX200
Firmware Version:                         5.9.0.13.0.2
API Version:                              4.17.18.6
XTSE Capabilities:                        0x0, 0x0, 0x0, 0x0, 0x0, 0x4, 0x0, 0x0
Annex:                                    B
Line Mode:                                G.992.5 (ADSL2+)
Profile:                                  
Line State:                               UP [0x801: showtime_tc_sync]
```
and hash
```
root@gw02:~# sha256sum /lib/firmware/vr9-B-dsl.bin
e408f82323fa60356d1c35df5b781f88d3fad830c7c6a55f798682e16316b939  /lib/firmware/vr9-B-dsl.bin
```

**Comment by pstlr78** [comment]
> 
> 
> ADSL:
> 
> ```
> Chipset:                                  Lantiq-VRX200
> Firmware Version:                         5.9.0.13.0.2
> API Version:                              4.17.18.6
> XTSE Capabilities:                        0x0, 0x0, 0x0, 0x0, 0x0, 0x4, 0x0, 0x0
> Annex:                                    B
> Line Mode:                                G.992.5 (ADSL2+)
> Profile:                                  
> Line State:                               UP [0x801: showtime_tc_sync]
> ```
> 
> and hash
> 
> ```
> root@gw02:~# sha256sum /lib/firmware/vr9-B-dsl.bin
> e408f82323fa60356d1c35df5b781f88d3fad830c7c6a55f798682e16316b939  /lib/firmware/vr9-B-dsl.bin
> ```

Any idea why my checksum is not the same? :

Name: vr9-B-dsl.bin
Size: 908376 bytes (887 KiB)
CRC32: 8E811D1D
CRC64: E80FB2A70EFC7C5A
SHA256: 8A676D7B7E07E34C9CC97F5350E04F73ABE68E21E9D52661E6169A4235E76A28
SHA1: CEACE0E9CCFA09372248371C2BAD4D7FC4CC9B35
BLAKE2sp: 6C78B0386818D5CA6E19319BF7C2B359CE9B738920F75EE29F853CB575573AC0

I obtained the firmware from 7490 (image 07.11).

Should not be a bad extract, because the checksums of the "release" versions are same as before.

**Comment by Lankaster** [comment]
@pstlr78 i think it's not v 5.9.0.13.0.2 (5.9.0.C.0.2) Maybe another minor version ?
Right now i use v5.7.8.9.1.7 it's really stable: uptime 37 days. Latest firmware is very instable for my: dsl reconnected every 2-8 hours (see openwrt forum).

**Comment by suppenkasper0815** [comment]
Hi, unfortunately I don't get the file extracted out of the firmware with 7z seems to get problems under Ubuntu. I also tried to install it separately with newest version, but always get stuck. - Is there a possibility for help of someone to get newest DSL driver?

**Comment by Lankaster** [comment]
@suppenkasper0815 You need 7z and **unsquashfs4-avm-be** tool to extract DSL firmware from AVM images. 
[Howto: Updating the Lantiq XRX200 devices with latest DSL vectoring firmware](https://forum.openwrt.org/t/howto-updating-the-lantiq-xrx200-devices-with-latest-dsl-vectoring-firmware/18853)
It seams the SVN Repo is die, but you can use [Github freetz Repo](https://github.com/Freetz/freetz)

**Comment by xdarklight** [comment]
is this still relevant for anyone now that I have added the xDSL firmware info from the 7490 production (non-testing/"Labor") image (see #19)?
if so, please speak up in the next week, else I'll close this
