### ISSUE TITLE
[Please help]I need to disable the interleaving and G.inp for better Ping latency and my isp is lazy and Ignorant! I need to ovveride it manually but don't know how.

### ISSUE THREAD

**Issue by skullface101** [xdarklight/lantiq-xdsl-firmware-info#17]
[Please help]I need to disable the interleaving and G.inp for better Ping latency and my isp is lazy and Ignorant! I need to ovveride it manually but don't know how.

My device is lantiq xrx 200
my loop length is short but my isp ignores my requests!
I am at profile 17a
I need you to help me with a patch that disable all sorts of error correction.
Or If possible provide commands to do what i need.

Thanks
Edit: btw ltq-xdsl-fw-info.sh	give error on my router TP-LINK 8970 v1 running OpenWRT 18.
"env: can't execute 'bash': No such file or directory"
And by removing the first line still there is errors
"./ltq-xdsl-fw-info.sh: line 43: syntax error: unexpected "(" (expecting "}")"

**Comment by xdarklight** [comment]
Hello,

this repository is about the xDSL firmware info binaries.
I don't know any way to modify these binaries (I can't even tell whether we are allowed to modify them).

If you want to change the modem settings then ``vdsl_cpe_control`` has to do this.
Personally I don't know whether that tool can configure the settings you want to change.
Please ask the OpenWrt guys and/or create an OpenWrt feature request.

Regarding the error on your TP-LINK 8970 v1:
> "env: can't execute 'bash': No such file or directory"
all following errors are expected, the script uses bashism and thus won't work without bash.
