### ISSUE TITLE
Firmware Versions 5.9.0.12.1.7 and 5.9.1.4.0.7

### ISSUE THREAD

**Issue by Sleepw4lker** [xdarklight/lantiq-xdsl-firmware-info#19]
Version: 5.9.0.12.1.7
URL: https://download.avm.de/fritzbox/fritzbox-7412/deutschland/fritz.os/FRITZ.Box_7412-06.86.image

D80506DD061C3915A65923A7D198DF94ADA3D745 vr9-A-dsl.bin
756553DCB16FFEE8BC1A92F13AE1670D6DB35A79 vr9-B-dsl.bin

Version: 5.9.1.4.0.7
URL: https://ftp.avm.de/fritzbox/fritzbox-7490/deutschland/fritz.os/FRITZ.Box_7490-07.12.image

4B27CEC814DEEFECCA912A974CF2B180548417FA vr9-A-dsl.bin
CEACE0E9CCFA09372248371C2BAD4D7FC4CC9B35 vr9-B-dsl.bin

Extraction:

7z e *.image -r filesystem.image
7z e filesystem.image filesystem_core.squashfs
unsquashfs4-avm-be filesystem_core.squashfs -e lib/modules/dsp_vr9/
cd lib/modules/dsp_vr9/
bspatch vr9-B-dsl.bin vr9-A-dsl.bin vr9-A-dsl.bin.bsdiff

**Comment by xdarklight** [comment]
I just updated the repo with your instructions
Thank your for letting me know
