### ISSUE TITLE
Unable to execute unsquashfs4-avm-be

### ISSUE THREAD

**Issue by KarstenDE** [xdarklight/lantiq-xdsl-firmware-info#22]
I am unable to execute the `unsquashfs4-avm-be` Command.

I tried to get it from freeze and from GitHub.com/PeterPawn but all with no success. Any hints?

Thanks!

**Comment by xdarklight** [comment]
the help text says:
> NOTE: unsquashfs4-avm-be is part of http://freetz.org/. You have to checkout the freetz source and build the tools (make tools) to get the binary.

so I tried this:
1. go to http://freetz.org/
2. click "Quellen durchsehen" on the top right
3. download that git repo
4. in the git repo, run ``make -j8 tools``
5. (wait for #4 to complete)

now I can execute ``./tools/unsquashfs4-avm-be`` successfully

Please give it a try and let me know if it works for you.
Also I'm happy to take suggestions on how to improve the text.

**Comment by KarstenDE** [comment]
Now it worked fine. Thanks!
