### ISSUE TITLE
firmware extraction issue

### ISSUE THREAD

**Issue by nouman8** [xdarklight/lantiq-xdsl-firmware-info#25]
Hi,
i can't extract the latest firmware of Fritzbox7490 version 7.21 released few days ago. 7z fails at this command 
7z e filesystem.image filesystem_core.squashfs
help me guys.

**Comment by nouman8** [comment]
managed to extract.
closing.

**Comment by Uka-Uka** [comment]
@nouman8 Hey bro! I get the same exact error! how did you manage to solve it?

**Comment by nouman8** [comment]
extract using "binwalk --extract filesystem.image" it will create 0.squash file which you can extract using the usual unsquashfs4-avm tool to get filesystem_core.squashfs file

**Comment by Uka-Uka** [comment]
Thanks for replying! I'm gonna clone the freetz repo, but there's something confusing me, 'unsquashfs4-avm-be' isn't there in the freetz repo tools folder, so how I'm supposed to run that tool if it's not there?

**Comment by xdarklight** [comment]
according to the extraction steps of `4b27cec814deefecca912a974cf2b180548417fa`:
> NOTE: unsquashfs4-avm-be is part of http://freetz.org/. You have to checkout the freetz source and build the tools (make tools) to get the binary. NOTE: p7zip version 15.09 or newer is required to extract the images.

so I tried this:
```
git clone https://github.com/Freetz/freetz/
cd freetz/
make -j8 tools
./tools/unsquashfs4-avm-be --help 
```

if that's not working for you then please discuss the problem with the freetz maintainers
