### ISSUE TITLE
Typo in download URL

### ISSUE THREAD

**Issue by nwholloway** [xdarklight/lantiq-xdsl-firmware-info#27]
Downloads for 5.9.1.4.0.7-5.9.0.D.0.2 has this as the download URL:

* https://ftp.avm.de/fritzbox/fritzbox-7490/deutschland/fritz.os/FRITZ.Box_7490-07.12.image

Examining the contents of the directory leads me to believe the link should be (last two digits transposed)

* https://ftp.avm.de/fritzbox/fritzbox-7490/deutschland/fritz.os/FRITZ.Box_7490-07.21.image

**Comment by nwholloway** [comment]
Progressing further I was unable to extract the firmware from the image downloaded on the other URL.

The "filesystem.image" file extracted from the download image only contained "filesystem" (a MIPS executable), and not "filesystem_core.squashfs" as expected.

**Comment by xdarklight** [comment]
> Examining the contents of the directory leads me to believe the link should be (last two digits transposed)

I think when the documentation was added version number 07.12 was correct

> Progressing further I was unable to extract the firmware from the image downloaded on the other URL.
> The "filesystem.image" file extracted from the download image only contained "filesystem" (a MIPS executable), and not "filesystem_core.squashfs" as expected.

I will remove the instruction for the relevant firmware blobs. we had this before, see 93e8251047d9f13537855fa26b53e0c0985afb21
We can always re-add them once someone knows how to extract the files from the new image

**Comment by micorcosmo** [comment]
just to clarify previous post: i use binwalk since 7z is giving me errors while extracting.
