### ISSUE TITLE
VDSL Annex J lantiq Firmware?!

### ISSUE THREAD

**Issue by tmuehlhoff** [xdarklight/lantiq-xdsl-firmware-info#29]
Hi,
in search for a Vectoring FW for my vr200v I stumbled over your collection. All listed VDSL firmwares are for Annex A or B. We have mainly Annex J here in Germany, do you think it makes sense to unpack an AVM image of a VR9 box supporting it ? Eg. a 7490 ? Eg. from http://acsfwdl.1und1.de/avm/7490/FRITZ.Box_7490.113.06.93.image ? But it also only contains Annex B and Annex A, maybe it's anyway contained in both ? (as it doesn't leave the spectrum gap for analog telephony?!)
BR/Tomas

**Comment by xdarklight** [comment]
Hi,

there is no "Annex" concept for VDSL.
Each blob contains two firmware images (which is why there's two "Firmware versions", two "Application Types" and two "Release Types" are listed for each file):
* a VDSL firmware, there is no Annex information here
* an ADSL firmware where the Annex type is relevant

What you are looking for in the wiki table is a firmware image where the "Application Type" column contains "VDSL over ISDN incl. vectoring support"

see also #24 for some hint as to which firmware you can try


Best regards,
Martin

**Comment by tmuehlhoff** [comment]
Thanks for replying. I was mislead by lots of, apparently stupid information on the Internet. My current DSL modem shows profile 17a ITU G.993.5. And I myself only remember good old ADSL times, where I was deeper in the matter. I'll try what's mentioned in the #24 ticket. Besides the FW itself... What would I need to configures ? Should I see something in the DSL stats on the OpenWRT overview already ? So far I only got "L3 - no power". Possibly I'm using wrong pinout ?! But I saw ONCE, only once in the logread that dsl0 came up.

Thanks a lot.

**Comment by tmuehlhoff** [comment]
btw. there seems to be only a .diff file for Annex A in what I unpacked (7490):
...
-rw-rw-rw- 1 root root 251523 Jan  2 21:20 release-vr9-A-dsl.bin.bsdiff
-rw-rw-rw- 1 root root     56 Jan  2 21:20 release-vr9-A-dsl.bin.md5sum
-rw-rw-rw- 1 root root 245399 Jan  2 21:20 release-vr9-B-dsl.bin.bsdiff
-rw-rw-rw- 1 root root     56 Jan  2 21:20 release-vr9-B-dsl.bin.md5sum
-rw-rw-rw- 1 root root    122 Jan  2 21:20 vr9-A-adsl.api.syms
-rw-rw-rw- 1 root root  82111 Jan  2 21:20 vr9-A-dsl.bin.bsdiff
-rw-rw-rw- 1 root root     48 Jan  2 21:20 vr9-A-dsl.bin.md5sum
-rw-rw-rw- 1 root root    122 Jan  2 21:20 vr9-B-adsl.api.syms
-rw-rw-rw- 1 root root   8192 Jan  2 21:20 vr9-B-calibrate.bin
-rw-rw-rw- 1 root root 907232 Jan  2 21:20 vr9-B-dsl.bin
-rw-rw-rw- 1 root root    154 Jan  2 21:20 vr9-vdsl.api.syms
...
but I understand I don't need to care here.

**Comment by xdarklight** [comment]
> Besides the FW itself... What would I need to configures ?

from the defaults OpenWrt ships with I have configured:
* username (self-explanatory)
* password (self-explanatory)
* ifname (to include the VLAN I am using "dsl0.7")

> Should I see something in the DSL stats on the OpenWRT overview already ? So far I only got "L3 - no power". Possibly I'm using wrong pinout ?! But I saw ONCE, only once in the logread that dsl0 came up.

you definitely should be seeing stats. if not, check your cable and/or try another DSL firmware blob.
from my connection:
```
# /etc/init.d/dsl_control dslstat
ATU-C Vendor ID:                          Broadcom 178.18
ATU-C System Vendor ID:                   Broadcom
Chipset:                                  Lantiq-VRX200
Firmware Version:                         5.8.1.5.0.7
API Version:                              4.17.18.6
XTSE Capabilities:                        0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x2
Annex:                                    B
Line Mode:                                G.993.5 (VDSL2 with down- and upstream vectoring)
Profile:                                  17a
Line State:                               UP [0x801: showtime_tc_sync]
Forward Error Correction Seconds (FECS):  Near: 0 / Far: 834
Errored seconds (ES):                     Near: 59 / Far: 286
Severely Errored Seconds (SES):           Near: 28 / Far: 51
Loss of Signal Seconds (LOSS):            Near: 2 / Far: 0
Unavailable Seconds (UAS):                Near: 51523122 / Far: 51523122
Header Error Code Errors (HEC):           Near: 0 / Far: 0
Non Pre-emtive CRC errors (CRC_P):        Near: 23 / Far: 0
Pre-emtive CRC errors (CRCP_P):           Near: 0 / Far: 0
Power Management Mode:                    L0 - Synchronized
Latency [Interleave Delay]:               0.13 ms [Fast]   0.0 ms [Fast]
Data Rate:                                Down: 63.668 Mb/s / Up: 12.735 Mb/s
Line Attenuation (LATN):                  Down: 12.1 dB / Up: 10.8 dB
Signal Attenuation (SATN):                Down: 12.1 dB / Up: 10.7 dB
Noise Margin (SNR):                       Down: 19.4 dB / Up: 27.8 dB
Aggregate Transmit Power (ACTATP):        Down: -1.7 dB / Up: 5.4 dB
Max. Attainable Data Rate (ATTNDR):       Down: 112.342 Mb/s / Up: 41.573 Mb/s
Line Uptime Seconds:                      201161
Line Uptime:                              2d 7h 52m 41s
```

> btw. there seems to be only a .diff file for Annex A in what I unpacked (7490):

AVM is doing some space-saving there. they're shipping the "Annex B" blob.
For Annex A regions they apply a patch to the "Annex B" blob -> the result of that patch is the "Annex A" blob
see the steps from the firmware with sha1sum ``d80506dd061c3915a65923a7d198df94ada3d745`` for example


Best regards,
Martin
