### ISSUE TITLE
Netgear VEVG2500 analysis

### ISSUE THREAD

**Issue by Weissnix4711** [xdarklight/lantiq-xdsl-firmware-info#32]
While looking through the netgear sources for the VEVG2500, I came across a few packages related to lantiq firmware. Sadly, there were no binaries, though I thought this information might still be useful to someone.

These versions must exist somewhere, and if anyone does have this device, they would probably be able to extract one of the following FW versions from it. There appears to be no complete firmware binary available to download from netgear's website, though this device it seems was primarily sold to ISPs, including the French 'Numerical', so maybe there are firmware downloads available elsewhere.

```
PKG_NAME:=ifx-dsl-amazon-se-firmware-adsl-a
PKG_VERSION:=03.04.07.0B.00.01

PKG_NAME:=ifx-dsl-amazon-se-firmware-adsl-b
PKG_VERSION:=03.04.01.07.00.02

PKG_NAME:=ifx-dsl-ar9-firmware-adsl-a
PKG_VERSION:=04.04.07.0B.00.01

PKG_NAME:=ifx-dsl-ar9-firmware-adsl-b
PKG_VERSION:=04.04.01.07.00.02

PKG_NAME:=ifx-dsl-danube-firmware-adsl-a
PKG_VERSION:=02.04.07.0B.00.01

PKG_NAME:=ifx-dsl-danube-firmware-adsl-b
PKG_VERSION:=02.04.01.07.00.02

PKG_NAME:=ifx-dsl-vinax-cpe-firmware-adsl-a
PKG_VERSION:=09.06.01.03.02.05

PKG_NAME:=ifx-dsl-vinax-cpe-firmware-adsl-b
PKG_VERSION:=09.05.02.01.00.06

PKG_NAME:=ifx-dsl-vinax-cpe-firmware-vdsl2
PKG_VERSION:=09.13.00.01.01.02

PKG_NAME:=ifx-dsl-vr9-firmware-xdsl
PKG_VERSION:=05.03.01.0A.01.06_05.03.03.00.01.01
```

I'm presuming these all refer to different SoCs, which may or may not be supported under xway. Aside from vr9, which would obviously be supported under xrx200. Does this site intend to list firmware for other SoCs as well, or just the vr9 family? In fact, does anyone know how well these other SoCs are supported in linux / openwrt anyway?

**Comment by xdarklight** [comment]
The `gh-pages` branch does support multiple chips - I just pushed info about the VRX500 firmware files.

If someone wants to document the firmware versions for older chips then I'm fine with that.
I'm not actively working on that though. So it would require someone with the time and interest to open a pull request.
