### ISSUE TITLE
How to extract DSL firmware ?

### ISSUE THREAD

**Issue by UnidentifiedTag** [xdarklight/lantiq-xdsl-firmware-info#33]
Hello all

1) I believe the "VMG1312-T20B" holds new DSL firmware, however im not sure how to extract it as nothing is in the firmware folder or the modules folder? all i know is, this works better on my line than the dm200/VRX200

https://www.zyxel.com/uk/en/support/download_library/product/vmg1312_t20b_14.shtml?c=uk&l=en&pid=20170103120002&tab=Firmware&pname=VMG1312-T20B&mtname=Firmware

https://download.zyxel.com/VMG1312-T20B/firmware/VMG1312-T20B_5.30(ABSB.5)C0.zip

2) im having problems with openwrt on dm200 under (21.02.3) it keeps rebooting, it connects to my dsl line under bridge mode then randomly reboots ?

**Comment by xdarklight** [comment]
Hello,

regarding your questions:
1. I'm not sure either - if anyone finds a way they can create a pull request
2. I don't have a DM200 myself. I suggest asking in the OpenWrt support channels (IRC, forum, ...)
