### ISSUE TITLE
xDSL files ("blobs") in recent Draytek Lantiq modem firmwares

### ISSUE THREAD

**Issue by aimacintyre** [xdarklight/lantiq-xdsl-firmware-info#34]
To extract an xDSL firmware file
- unpack the firmware files (.all, .rst) from the release .zip
  (it doesn't matter whether the .all or .rst variant is used,
   the output image will have the same content for any given firmware release)
- execute
    `extract_dtv_fw.py <firmware_file>`
  (the output will be named firmware_file.fw)
- execute
    `extract_ltq_xdsl_files.py <firmware_file.fw>`
  (any xDSL files found will be extracted to the current working directory)

The above Python scripts are available from
https://github.com/aimacintyre/xdsl-modem-fw-tools  

The xDSL file versions I've identified to date are listed below grouped
by Draytek device.  I haven't tried to remove any duplicates that may
already be in the VRX200 public list, or the duplicates between different
Draytek firmwares.  The filename shown in the list is that of the firmware image extracted from
the device firmware .all file using the `extract_dtv_fw.py` script.

Example:
```
wget https://fw.draytek.com.tw/Vigor130/Firmware/v3.8.4.1/Vigor130_v3.8.4.1_STD.zip
unzip Vigor130_v3.8.4.1_STD.zip
extract_dtv_fw.py v130_3841_modem_STD.all
extract_ltq_xdsl_files.py v130_3841_modem_STD.all.fw
```
The output of `extract_ltq_xdsl_files.py`:
```
[1]  xDSL file with type A start marker found:
     offset:  0x65f138
     length:  815532 bytes
     version: 5.4.8.0.0.6_5.4.4.4.0.1
[2]  xDSL file with type A start marker found:
     offset:  0x7262e8
     length:  802032 bytes
     version: 5.4.8.0.0.6_5.4.4.5.1.2
```
The extracted xDSL files:
```
ls -l *.bin
-rw-rw-r-- 1 andymac andymac 815532 Jul 12 16:59 xcpe_5.4.8.0.0.6_5.4.4.4.0.1.bin
-rw-rw-r-- 1 andymac andymac 802032 Jul 12 16:59 xcpe_5.4.8.0.0.6_5.4.4.5.1.2.bin
```
I have successfully run the following extracted file versions in several devices on my VDSL2 service:
- 5.7.C.8.1.7_5.7.5.A.1.1 (TP-Link TD-W8980, Openwrt master with the vectoring fixes)
- 7.7.C.8.1.7_7.7.5.A.1.1 (Netgear D7000v2 & D7800, spliced into factory firmware)

---

Vigor 130 (VRX200/VR9)
- https://fw.draytek.com.tw/Vigor130/Firmware/v3.8.4.1/

v130_3841_modem_STD.all.fw  (Vigor130_v3.8.4.1_STD.zip)
  5.4.8.0.0.6_5.4.4.4.0.1  (815532 bytes)
  5.4.8.0.0.6_5.4.4.5.1.2  (802032 bytes)

v130_3841_modem_1.all.fw  (Vigor130_v3.8.4.1_modem_1.zip)
  5.4.7.9.1.6_5.4.4.4.1.1  (816668 bytes)
  V_5.4.2.0.1.6_5.3.5.1.1.2  (759792 bytes)

v130_3841_modem_2.all.fw  (Vigor130_v3.8.4.1_modem_2.zip)
  5.5.0.E.0.6_5.5.1.0.0.1  (845596 bytes)
  V_5.3.3.D.0.6_5.3.5.9.0.2  (759904 bytes)

v130_3841_modem_3.all.fw  (Vigor130_v3.8.4.1_modem_3.zip)
  5.4.8.0.0.6_5.4.4.5.1.2  (802032 bytes)
  5.5.1.5.0.6_5.5.1.5.0.1  (846016 bytes)

v130_3841_modem_4.all.fw  (Vigor130_v3.8.4.1_modem_4.zip)
  5.7.6.D.1.7_5.7.2.8.0.1  (927224 bytes)
  5.7.3.3.0.7_5.7.1.5.0.2  (904184 bytes)

v130_3841_modem_5.all.fw  (Vigor130_v3.8.4.1_modem_5.zip)
  5.7.1.A.1.7_5.7.0.1.1.1  (910420 bytes)
  5.6.5.6.0.7_5.6.7.0.0.2  (891056 bytes)

v130_3841_modem_6.all.fw  (Vigor130_v3.8.4.1_modem_6.zip)
  5.6.5.6.0.7_5.6.7.0.0.2  (891056 bytes)
  5.7.2.D.0.7_5.7.0.E.0.1  (919740 bytes)

v130_3841_modem_7.all.fw  (Vigor130_v3.8.4.1_modem_7.zip)
  5.6.7.5.1.7_5.6.2.3.0.1  (901132 bytes)
  5.6.7.6.1.7_5.6.7.2.1.2  (877836 bytes)

v130_3841_modem_8.all.fw  (Vigor130_v3.8.4.1_modem_8.zip)
  5.7.9.F.1.7_5.7.3.F.0.1  (928764 bytes)
  5.7.3.3.0.7_5.7.1.5.0.2  (904184 bytes)

v130_3841_modem_9.all.fw  (Vigor130_v3.8.4.1_modem_9.zip)
  5.7.4.3.0.7_5.7.1.8.0.1  (923140 bytes)
  5.7.3.3.0.7_5.7.1.5.0.2  (904184 bytes)

v130_3841_modem_10.all.fw  (Vigor130_v3.8.4.1_modem_10.zip)
  5.7.C.7.1.7_5.7.5.A.1.1  (950268 bytes)
  5.7.3.3.0.7_5.7.1.5.0.2  (904184 bytes)

v130_3841_modem_11.all.fw  (Vigor130_v3.8.4.1_modem_11.zip)
  5.7.C.8.1.7_5.7.5.A.1.1  (950272 bytes)
  5.7.3.3.0.7_5.7.1.5.0.2  (904184 bytes)

---

Vigor 2760-Delight (VRX200/VR9)
- https://fw.draytek.com.tw/Vigor2760-Delight/Firmware/v3.8.9.5/

v2760_std_3895.all.fw  (Vigor2760_v3.8.9.5_STD.zip)
  5.4.8.0.0.6_5.4.4.4.0.1  (815532 bytes)
  5.5.1.7.1.6_5.5.3.3.1.2  (830312 bytes)
  5.4.8.0.0.6_5.4.4.5.1.2  (802032 bytes)

v2760_vect1_3895.all.fw  (Vigor2760_v3.8.9.5_VECTOR1.zip)
  5.6.6.F.0.7_5.6.2.7.0.1  (901204 bytes)
  5.6.7.5.1.7_5.6.2.3.0.1  (901132 bytes)
  5.6.5.6.0.7_5.6.7.0.0.2  (891056 bytes)
  5.6.5.6.0.6_5.6.7.0.0.2  (891064 bytes)

v2760_vect2_3895.all.fw  (Vigor2760_v3.8.9.5_VECTOR2.zip)
  5.7.3.8.0.7_5.7.1.7.0.1  (919952 bytes)
  5.7.4.3.0.7_5.7.1.8.0.1  (923140 bytes)
  5.7.3.3.0.7_5.7.1.C.0.2  (904388 bytes)
  5.6.5.6.0.7_5.6.7.0.0.2  (891056 bytes)

v2760_vect3_3895.all.fw  (Vigor2760_v3.8.9.5_VECTOR3.zip)
  5.7.6.D.1.7_5.7.2.8.0.1  (927224 bytes)
  5.7.4.3.0.7_5.7.1.8.0.1  (923140 bytes)
  5.7.3.3.0.7_5.7.1.C.0.2  (904388 bytes)
  5.6.5.6.0.7_5.6.7.0.0.2  (891056 bytes)

v2760_vect4_3895.all.fw  (Vigor2760_v3.8.9.5_VECTOR4.zip)
  5.7.3.8.0.7_5.7.1.7.0.1  (919952 bytes)
  5.7.9.F.1.7_5.7.3.F.0.1  (928764 bytes)
  5.7.3.3.0.7_5.7.1.C.0.2  (904388 bytes)
  5.6.5.6.0.7_5.6.7.0.0.2  (891056 bytes)

v2760_vect5_3895.all.fw  (Vigor2760_v3.8.9.5_VECTOR5.zip)
  5.7.C.8.1.7_5.7.5.A.1.1  (950272 bytes)
  5.7.3.8.0.7_5.7.1.7.0.1  (919952 bytes)
  5.7.3.3.0.7_5.7.1.C.0.2  (904388 bytes)
  5.6.5.6.0.7_5.6.7.0.0.2  (891056 bytes)

---

Vigor 2762 (VRX300/VR10)
- https://fw.draytek.com.tw/Vigor2762/Firmware/v3.9.6.3/

v2762_std_3963.all.fw  (Vigor2762_v3.9.6.3_STD.zip)
  7.7.6.D.0.7_7.7.2.8.0.1  (940144 bytes)
  7.7.3.3.0.6_7.7.1.5.0.2  (918736 bytes)
  7.7.3.3.0.7_7.7.1.C.0.2  (918896 bytes)
  7.7.4.3.0.7_7.7.1.8.0.1  (936240 bytes)

v2762_mdm1_3963.all.fw  (Vigor2762_v3.9.6.3_MDM1.zip)
  7.7.9.5.1.7_7.7.3.F.0.1  (940644 bytes)
  7.7.B.5.0.7_7.7.5.4.0.1  (959380 bytes)
  7.7.9.B.0.7_7.7.4.C.1.2  (940024 bytes)
  7.7.9.B.0.6_7.7.4.F.0.2  (939984 bytes)

v2762_mdm2_3963.all.fw  (Vigor2762_v3.9.6.3_MDM2.zip)
  7.7.8.C.0.6_7.7.3.F.0.1  (940656 bytes)
  7.7.B.5.0.6_7.7.5.4.0.1  (959396 bytes)
  7.7.9.B.0.6_7.7.4.C.0.2  (940040 bytes)
  7.7.9.9.0.6_7.7.4.4.0.2  (939124 bytes)

v2762_mdm3_3963.all.fw  (Vigor2762_v3.9.6.3_MDM3.zip)
  7.7.C.8.1.7_7.7.5.A.1.1  (959744 bytes)
  7.7.C.7.1.7_7.7.5.A.1.1  (959744 bytes)
  7.7.9.B.0.7_7.7.4.C.1.2  (940024 bytes)
  7.7.C.7.1.7_7.7.5.A.1.2  (944432 bytes)

---

Vigor 165 (VRX500/VR11)
- https://fw.draytek.com.tw/Vigor165/Firmware/v4.2.3.1/

v165_std_4231.all.fw  (Vigor165_v4.2.3.1_STD.zip)
  8.B.2.6.0.7_8.B.0.B.0.1  (960032 bytes)
  8.B.0.F.0.7_8.B.0.7.0.1  (950452 bytes)
  8.B.2.6.0.7_8.B.0.B.0.2  (942704 bytes)
  8.B.2.8.1.7_8.B.0.8.1.2  (934016 bytes)

v165_mdm1_4231.all.fw  (Vigor165_v4.2.3.1_MDM1.zip)
  8.B.1.1.1.7_8.B.0.7.0.1  (950752 bytes)
  8.B.0.F.0.7_8.B.0.7.0.1  (950452 bytes)
  8.B.2.6.0.7_8.B.0.B.0.2  (942704 bytes)
  8.B.2.8.1.7_8.B.0.8.1.2  (934016 bytes)

v165_mdm2_4231.all.fw  (Vigor165_v4.2.3.1_MDM2.zip)
  8.D.1.5.0.7_8.D.0.9.0.1  (1005436 bytes)
  8.D.1.9.1.7_8.D.0.C.1.1  (1028136 bytes)
  8.D.1.9.1.7_8.D.0.C.1.2  (1007624 bytes)
  8.B.2.8.1.7_8.B.0.8.1.2  (934016 bytes)

v165_mdm3_4231.all.fw  (Vigor165_v4.2.3.1_MDM3.zip)
  8.D.1.5.0.7_8.D.0.9.0.1  (1005436 bytes)
  8.D.1.9.1.7_8.D.0.C.1.1  (1028136 bytes)
  8.B.2.6.0.7_8.B.0.B.0.2  (942704 bytes)
  8.D.1.9.1.7_8.D.0.C.1.2  (1007624 bytes)

---

Vigor 2765 (VRX500/VR11)
- https://fw.draytek.com.tw/Vigor2765/Firmware/v4.4.1/

v2765_std_441.all.fw  (Vigor2765_v4.4.1_STD.zip)
  8.B.2.6.0.7_8.B.0.B.0.1  (960032 bytes)
  8.B.0.F.0.7_8.B.0.7.0.1  (950452 bytes)
  8.B.2.6.0.7_8.B.0.B.0.2  (942704 bytes)
  8.B.2.8.1.7_8.B.0.8.1.2  (934016 bytes)

v2765_mdm1_441.all.fw  (Vigor2765_v4.4.1_MDM1.zip)
  8.B.1.1.1.7_8.B.0.7.0.1  (950752 bytes)
  8.B.0.F.0.7_8.B.0.7.0.1  (950452 bytes)
  8.B.2.6.0.7_8.B.0.B.0.2  (942704 bytes)
  8.B.2.8.1.7_8.B.0.8.1.2  (934016 bytes)

v2765_mdm2_441.all.fw  (Vigor2765_v4.4.1_MDM2.zip)
  8.D.1.5.0.7_8.D.0.9.0.1  (1005436 bytes)
  8.D.1.9.1.7_8.D.0.C.1.1  (1028136 bytes)
  8.D.1.9.1.7_8.D.0.C.1.2  (1007624 bytes)
  8.B.2.8.1.7_8.B.0.8.1.2  (934016 bytes)

v2765_mdm3_441.all.fw  (Vigor2765_v4.4.1_MDM3.zip)
  8.D.1.5.0.7_8.D.0.9.0.1  (1005436 bytes)
  8.D.1.9.1.7_8.D.0.C.1.1  (1028136 bytes)
  8.B.2.6.0.7_8.B.0.B.0.2  (942704 bytes)
  8.D.1.9.1.7_8.D.0.C.1.2  (1007624 bytes)

v2765_mdm4_441.all.fw  (Vigor2765_v4.4.1_MDM4.zip)
  8.D.1.C.1.7_8.D.0.E.1.1  (1030708 bytes)
  8.D.1.B.1.7_8.D.0.E.1.1  (1030736 bytes)
  8.D.1.9.1.7_8.D.0.C.1.2  (1007624 bytes)
  8.D.1.C.1.7_8.D.0.E.1.2  (1010220 bytes)

**Comment by kissmorning** [comment]
Can anyone extract the files? I couldn't. Can you share the xdsl file?

**Comment by andyboeh** [comment]
The procedure worked fine for me with a 4.4.2 v2765 firmware. Sharing is probably not allowed, but we can try to help you getting the files extracted. Where are you stuck at?

**Comment by nicefile** [comment]
thx that's worked for
v130_385_modem_BT.all
786ccd97d2ecc0e94fc9fbb0e1388930  xcpe_5.6.5.6.0.7_5.6.7.0.0.2.bin
e5c69f0dfc79d63bdd2265e050c766dd  xcpe_5.7.3.3.0.7_5.7.1.C.0.2.bin
834df2c4bd6b1f726cbd644222bd9272  xcpe_5.7.6.D.1.7_5.7.2.8.0.1.bin
e4e8b72446eb78126be401cd19991c5c  xcpe_5.7.8.6.1.7_5.7.2.8.0.1.bin

xcpe_5.6.5.6.0.7_5.6.7.0.0.2.bin: VDSL over ISDN incl. vectoring support for VRX200, version: 6.5.6 | ADSL Annex B for VRX200, version: 6.7.0
xcpe_5.7.3.3.0.7_5.7.1.C.0.2.bin: VDSL over ISDN incl. vectoring support for VRX200, version: 7.3.3 | ADSL Annex B for VRX200, version: 7.1.C
xcpe_5.7.6.D.1.7_5.7.2.8.0.1.bin: VDSL over ISDN incl. vectoring support for VRX200, version: 7.6.D | ADSL Annex A for VRX200, version: 7.2.8
xcpe_5.7.8.6.1.7_5.7.2.8.0.1.bin: VDSL over ISDN incl. vectoring support for VRX200, version: 7.8.6 | ADSL Annex A for VRX200, version: 7.2.8

**Comment by xdarklight** [comment]
Thanks, with a small shell script I was able to batch-extract all data for Vigor130 and Vigor2765.
I omitted Vigor165 because it's EOL and is replaced by Vigor2765
I also omitted Vigor2762 because I am not sure if anyone managed to get this working on OpenWrt yet.
```shell
#!/usr/bin/env bash

BASEDIR="/tmp/draytek"

rm -rf "${BASEDIR}"
mkdir "${BASEDIR}"
cd "${BASEDIR}"

# for DEVICE in Vigor130 Vigor2762 Vigor165 Vigor2765
for DEVICE in Vigor130 Vigor2765
do
	VERSION=$(curl -s "https://fw.draytek.com.tw/${DEVICE}/Firmware/latest.txt")

	mkdir "${BASEDIR}/${DEVICE}"
	cd "${BASEDIR}/${DEVICE}"

	curl -O "https://fw.draytek.com.tw/${DEVICE}/Firmware/v${VERSION}/FIRMWARE.DIGESTS"

	for FILE in $(grep -Eo "[A-Za-z0-9_.]+.zip" FIRMWARE.DIGESTS)
	do
		curl -O "https://fw.draytek.com.tw/${DEVICE}/Firmware/v${VERSION}/${FILE}"

		unzip $FILE
	done

	for FILE in $(ls -1v *.all)
	do
		rm -f firmware_file.fw
		mkdir "_${FILE}"
		python /tmp/xdsl-modem-fw-tools/extract_dtv_fw.py "${FILE}"
		mv "${FILE}.fw" "_${FILE}/fw"
		cd "_${FILE}/"
		python /tmp/xdsl-modem-fw-tools/extract_ltq_xdsl_files.py "fw"
		cd ..
	done
done
```
