### ISSUE TITLE
DM200 - Firmware for Australia - NBN compatible

### ISSUE THREAD

**Issue by oam7575** [xdarklight/lantiq-xdsl-firmware-info#6]
Hi I have extracted the fimware for Netgear DM200 
It contains an updated Lantiq XRXV200 fimrware that apparently supports Australian NBN Fibre to the Node.

Full Netgear firmware can be downloaded here : http://www.downloads.netgear.com/files/GDC/DM200/DM200_V1.0.0.36.zip

The firmware can be extracted using binwalk -e DM200-V1.0.0.36.img

Fimware is located under : _DM200-V1.0.0.36.img.extracted/squashfs-root

OAM

**Comment by xdarklight** [comment]
Thanks for reporting this!
I went with some steps that don't require binwalk (by using the GPL tarball).
